<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="surapaneni" ignored="1" name="Personal loan" tests="5" failures="1" timestamp="2020-10-14T17:48:25 IST" time="0.204" errors="0">
  <testcase name="Demo" time="0.031" classname="test.day1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.Demo(day1.java:22)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase name="ploan" time="0.002" classname="test.day2"/>
  <testcase name="LoginAPIHomeLoan" time="0.004" classname="test.day4"/>
  <testcase name="MobileLoginHomeLoan" time="0.005" classname="test.day4"/>
  <testcase name="WebloginHomeLoan" time="0.003" classname="test.day4"/>
  <testcase name="SecondTest" time="0.0" classname="test.day1">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
